### ISSUE TITLE
Unable to install via Pypi and source

### ISSUE THREAD

**Issue by kpriyanshu256** [facebookresearch/bitsandbytes#28]
Installation via pip was working a few hours ago.
Now, I am getting the following error.

![image](https://user-images.githubusercontent.com/29113340/183573914-c133308f-fe7a-4f20-8076-9866b5efd573.png)

I am also unable to install from source.

![image](https://user-images.githubusercontent.com/29113340/183574591-e9ccb95a-c4d9-472e-bde5-f2460a8ad0fe.png)

**Comment by prajdabre** [comment]
So its not just me!

**Comment by hotchpotch** [comment]
me too. The installation method may have changed.

- https://github.com/facebookresearch/bitsandbytes/pull/27/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R5

```
pip install bitsandbytes
```

**Comment by kpriyanshu256** [comment]
I get the following logs on a P100 while using `pip install bitsandbytes`

`CUDA SETUP: CUDA path found: /usr/local/cuda/lib64/libcudart.so`
`CUDA SETUP: Highest compute capability among GPUs detected: 6.0`
`CUDA_SETUP: Detected CUDA version 110`
`CUDA_SETUP: Loading binary /opt/conda/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so...`
`Device with CUDA capability of 6 not supported for 8-bit matmul. Device has no tensor cores!`

**Comment by EpilodieResearch** [comment]
@TimDettmers @SirRob1997 Page, production outage, pypi with historical versions has been deleted, please restore ASAP and put forward migration plan as needed, software is currently broken which depends upon this and has different CUDA versions than the most recent CUDA version.

Many thanks.

**Comment by EpilodieResearch** [comment]
Impacted Pypi repos appear to include at least bitsandbytes-cuda110, bitsandbytes-cuda111, bitsandbytes-cuda112, bitsandbytes-cuda112. What caused such a big wipe? That's multiple sites at once, very surprising.

**Comment by EpilodieResearch** [comment]
Okay, I went ahead and sent an email to Tim via the email address provided on the new PyPi repo, `dettmers@cs.washington.edu`.

**Comment by TimDettmers** [comment]
We are releasing a major feature update tomorrow, and this repository will no longer be supported. Please now use instead:
`pip install bitsandbytes`

**Comment by EpilodieResearch** [comment]
Hi Tim,

As addressed here -- the version included there only unfortunately supports newer versions of NVIDIA cards. One of the difficult parts of creating a library with visibility and variety of supported architectures likes this requires providing ample time for legacy transitions for individuals/organizations. Many of us cannot magic our <Tesla cards into being Tesla, and many of us need the stability to an old pinned version, rather than needing to pivot for breaking changes.

This is rather out of standard form for a library -- having a new library is great, but I don't see what the downside of maintaining the legacy versions is. Right now, this change is well-intentioned but breaks a lot of code in a way that is not fixable, and was not broadcast ahead of time.

Even a deprecation warning followed by ending of support could be helpful. Simply deleting PyPi repos is generally unprecedented and accidentally scorched-earths current users on the library. If I were a production engineer, knowing that could happen in the future would be too much of a risk to take.

If you could restore the old PyPis, that would be fantastic. No new development needs to happen, but please don't try to force developers to use a particular version of a library. Many thanks.

**Comment by TimDettmers** [comment]
I think I made a mistake by deleting the old PyPi projects, I apologize.

I am not sure if I can make it today to build a new deprecated version of the library.

We will release a beta for general Int8 models tomorrow. For that, I am also not sure if I can make it until tomorrow to compile against CUDA versions < 11.0. One thing that you can always do is compile from the source if you need compatibility now.

Support for legacy features for versions > 9.2 are planned but are currently not a priority.

**Comment by TimDettmers** [comment]
Legacy support has mostly been restored. You can do
```bash
pip install bitsandbytes-cuda102
```
However, currently, I was not able to compile with CUDA 9.2. Let me know if this causes issues and I will try to compile later today.

Sorry for the inconvenience! Let me know if you run into issues!
